<?php
/**
 * Coimbatore Assembly Constituencies – Tamil Nadu 2026
 * Six ACs in Coimbatore Lok Sabha segment; optionally Thondamuthur (119).
 * Keyed by slug for constituency pages and know-your-constituency.
 */
return [
    'palladam' => [
        'name' => 'Palladam',
        'ac_no' => 115,
        'district' => 'Coimbatore',
        'areas' => ['Palladam', 'surrounding areas'],
        'winner_2021' => 'M.S.M. Anandan',
        'runner_up_2021' => 'Muthurathinam K',
        'winner_party_2021' => 'AIADMK',
        'runner_party_2021' => 'DMK',
        'winner_votes_2021' => 126903,
        'runner_votes_2021' => 94212,
        'margin_2021' => 32691,
    ],
    'sulur' => [
        'name' => 'Sulur',
        'ac_no' => 116,
        'district' => 'Coimbatore',
        'areas' => ['Sulur', 'surrounding areas'],
        'winner_2021' => 'V.P. Kandasamy',
        'runner_up_2021' => null,
        'winner_party_2021' => 'AIADMK',
        'runner_party_2021' => null,
        'winner_votes_2021' => 118968,
        'runner_votes_2021' => null,
        'margin_2021' => null,
    ],
    'kavundampalayam' => [
        'name' => 'Kavundampalayam',
        'ac_no' => 117,
        'district' => 'Coimbatore',
        'areas' => ['Kavundampalayam', 'surrounding areas'],
        'winner_2021' => 'G. Arunkumar',
        'runner_up_2021' => 'R. Krishnan',
        'winner_party_2021' => 'AIADMK',
        'runner_party_2021' => 'DMK',
        'winner_votes_2021' => 135669,
        'runner_votes_2021' => 125893,
        'margin_2021' => 9776,
    ],
    'coimbatore-north' => [
        'name' => 'Coimbatore (North)',
        'ac_no' => 118,
        'district' => 'Coimbatore',
        'areas' => ['Parts of Coimbatore city (North)'],
        'winner_2021' => 'Amman K. Arjunan',
        'runner_up_2021' => 'Shanmugasundaram V. M.',
        'winner_party_2021' => 'AIADMK',
        'runner_party_2021' => 'DMK',
        'winner_votes_2021' => 81454,
        'runner_votes_2021' => 77453,
        'margin_2021' => 4001,
    ],
    'coimbatore-south' => [
        'name' => 'Coimbatore (South)',
        'ac_no' => 120,
        'district' => 'Coimbatore',
        'areas' => ['Parts of Coimbatore city (South)'],
        'winner_2021' => 'Vanathi Srinivasan',
        'runner_up_2021' => 'Amman K. Arjunan',
        'winner_party_2021' => 'BJP',
        'runner_party_2021' => 'AIADMK',
        'winner_votes_2021' => null,
        'runner_votes_2021' => null,
        'margin_2021' => 1700,
    ],
    'singanallur' => [
        'name' => 'Singanallur',
        'ac_no' => 121,
        'district' => 'Coimbatore',
        'areas' => ['Singanallur', 'Coimbatore International Airport', 'Singanallur Bus Terminus', 'Sungam Lake', 'Boat House', 'TIDEL Park Coimbatore', 'ESI Medical College Hospital', '18 wards of Coimbatore'],
        'winner_2021' => 'K. R. Jayaram',
        'runner_up_2021' => 'N. Karthik',
        'winner_party_2021' => 'AIADMK',
        'runner_party_2021' => 'DMK',
        'winner_votes_2021' => 81244,
        'runner_votes_2021' => 70390,
        'margin_2021' => 10854,
    ],
];
