-- MyCovai: Seed schools (omr_schools) with Coimbatore schools
-- Target DB: metap8ok_mycovai
-- Run after main structure import.

INSERT INTO `omr_schools` (`school_id`, `school_name`, `address`, `city`, `pincode`, `curriculum`, `fees_annual`, `contact_number`, `email`, `website`, `established_year`, `grades_offered`, `student_teacher_ratio`, `total_students`, `rating`, `infrastructure`, `extracurricular`, `transport_available`, `boarding_available`, `principal_name`, `affiliation_number`, `medium_of_instruction`, `admission_process`, `last_updated`, `google_maps_link`) VALUES
(1, 'PSG Sarvajana Higher Secondary School', 'Avinashi Road, Peelamedu', 'Coimbatore', '641004', 'State Board', 25000.00, '0422 257 2345', 'school@psg.in', 'https://www.psgps.org', 1926, '1-12', '25:1', 3500, 4.5, 'Labs, library, sports', 'Sports, arts, NCC', 1, 0, NULL, NULL, 'Tamil, English', 'Merit and application', NOW(), NULL),
(2, 'Sri Krishna International School', 'Kovaipudur, Coimbatore', 'Coimbatore', '641042', 'CBSE', 85000.00, '0422 262 5678', 'info@skis.in', 'https://www.srikrishnaschool.org', 1995, 'LKG-12', '20:1', 2800, 4.4, 'Smart classes, labs', 'Sports, robotics, music', 1, 0, NULL, NULL, 'English', 'Entrance and application', NOW(), NULL),
(3, 'Bharatiya Vidya Bhavan', 'Race Course Road', 'Coimbatore', '641018', 'CBSE', 70000.00, '0422 221 3456', 'bvb@bhavans.net', 'https://www.bhavanscovai.org', 1982, 'LKG-12', '22:1', 2200, 4.3, 'Library, labs, auditorium', 'Sports, cultural', 1, 0, NULL, NULL, 'English', 'Application and interaction', NOW(), NULL),
(4, 'SBOA School and Junior College', 'Avinashi Road, Civil Aerodrome Post', 'Coimbatore', '641014', 'State Board, CBSE', 45000.00, '0422 257 8901', 'sboa@sboadschool.com', 'https://www.sboadschool.com', 1975, 'LKG-12', '24:1', 3000, 4.2, 'Labs, playground', 'Sports, clubs', 1, 0, NULL, NULL, 'English, Tamil', 'Merit', NOW(), NULL),
(5, 'St. Francis Anglo-Indian Higher Secondary School', 'Hopes College Road, Coimbatore', 'Coimbatore', '641018', 'State Board', 35000.00, '0422 221 2345', 'stfrancis@sfais.in', NULL, 1885, '1-12', '26:1', 2500, 4.3, 'Heritage campus, labs', 'Sports, music', 1, 0, NULL, NULL, 'English', 'Application', NOW(), NULL);
