-- MyCovai: Editorial starter events (Mar–Apr 2026 window)
-- Run ONLY after `event_categories` exists and IDs 1–5 match seed-covai-event-job-categories.sql
-- VERIFY dates, venues and ticketing on official sources before applying to LIVE.
-- Sandbox first. Slugs must be unique in `event_listings`.
-- INSERT IGNORE: safe to re-run on live; existing slugs are skipped, new slugs are inserted.

SET NAMES utf8mb4;

INSERT IGNORE INTO `event_listings` (
  `title`, `slug`, `category_id`, `organizer_id`, `organizer_name`, `organizer_email`, `organizer_phone`,
  `location`, `locality`, `start_datetime`, `end_datetime`, `is_all_day`, `is_free`, `price`, `tickets_url`, `website_url`, `image_url`, `description`, `featured`, `status`
) VALUES
(
  'Coimbatore Maasi Mahotsavam (Carnatic evenings)',
  'coimbatore-maasi-mahotsavam-2026',
  4,
  NULL,
  'MyCovai Editorial',
  'mycovai@gmail.com',
  '',
  'Sri Ayyappa Pooja Sangam, Ram Nagar, Coimbatore',
  'RS Puram',
  '2026-02-28 18:30:00',
  '2026-03-01 20:30:00',
  0,
  1,
  '',
  '',
  '',
  '',
  'Evening Carnatic concerts as part of the Maasi season in Coimbatore. Times and artist line-up can change—please confirm with the organising committee or local listings before you travel.',
  1,
  'scheduled'
),
(
  'VIHANSA 2026 – National techno-cultural fest (SRIT)',
  'vihansa-2026-sri-ramakrishna-institute-of-technology',
  2,
  NULL,
  'MyCovai Editorial',
  'mycovai@gmail.com',
  '',
  'Sri Ramakrishna Institute of Technology, Pachapalayam, Coimbatore',
  'Saravanampatti',
  '2026-03-13 09:00:00',
  '2026-03-14 18:00:00',
  0,
  0,
  'From ₹300',
  'https://www.knowafest.com/explore/events/2026/02/2381-vihansa-2026-sri-ramakrishna-institute-technology-national-level-techno-cultural-fest-coimbatore',
  '',
  '',
  'National-level technical and cultural events at SRIT. Registration fees and schedule vary by contest—check the official college / fest pages for the latest.',
  1,
  'scheduled'
),
(
  'Holi celebration – Gandhipuram (ticketed)',
  'holi-celebration-coimbatore-gandhipuram-mar-2026',
  1,
  NULL,
  'MyCovai Editorial',
  'mycovai@gmail.com',
  '',
  'Corporation Ground, Gandhipuram, Coimbatore',
  'Gandhipuram',
  '2026-03-14 18:00:00',
  '2026-03-14 21:00:00',
  0,
  0,
  'From ₹399',
  'https://www.ticketprix.com/event/holi',
  '',
  '',
  'Community Holi programme (ticketed). Venue layout, timings and inclusions can change—confirm on the official ticketing page before purchase.',
  0,
  'scheduled'
),
(
  'HackXelerate''26 – KPR Institute of Engineering and Technology',
  'hackxelerate-26-kpr-iet-coimbatore',
  2,
  NULL,
  'MyCovai Editorial',
  'mycovai@gmail.com',
  '',
  'KPR Institute of Engineering and Technology, Arasur, Coimbatore',
  'Saravanampatti',
  '2026-04-17 09:00:00',
  '2026-04-18 18:00:00',
  0,
  0,
  'As per organiser',
  'https://www.knowafest.com/explore/events/2026/02/1224-hackxelerate-26-kpr-institute-engineering-technology-hackathon-coimbatore',
  '',
  '',
  'Hackathon focused on real-world problem statements. Teams, themes and registration windows are set by the institute—refer to KPR IET / fest notices for accuracy.',
  1,
  'scheduled'
),
(
  'National Conference on Recent Advances in Engineering and Technology (NCRAET)',
  'ncraet-coimbatore-april-2026',
  2,
  NULL,
  'MyCovai Editorial',
  'mycovai@gmail.com',
  '',
  'Coimbatore (venue TBC – confirm with organisers)',
  'Peelamedu',
  '2026-04-25 09:00:00',
  '2026-04-25 17:00:00',
  0,
  0,
  'As per organiser',
  'https://conferencealerts.co.in/event/101011062',
  '',
  '',
  'Academic conference listing; exact hall address and registration fees must be taken from the organiser’s final programme / CFP. Replace this row after verification.',
  0,
  'scheduled'
);
